// Derives POSITION keys for the opening book from the move sequences already in
// the repo, and writes src/lib/ecoPositions.ts.
//
// Why positions and not sequences: matching the book by move ORDER meant any
// transposition left the book instantly. A real case from a played game —
// `e4 c6 Nf3 d5 e5 Bf5 d4` — reaches a position the book DOES contain, stored as
// `e4 c6 d4 d5 e5 Bf5 Nf3`. Same position, different order. We called it
// out-of-book from move 3, so ten theory moves got generic comments and the
// "theory ends here" marker fired far too early. Chess.com gets this right
// because it matches positions.
//
// Reads ECO_LINES out of the generated file rather than re-fetching upstream, so
// it only depends on data that's committed. (genOpenings.cjs needs the
// lichess-org TSV, which isn't in the repo.)
//
// Hashed to 32-bit integers: the raw position strings are 467KB, the hashes are
// 82KB with zero collisions across all 7850 positions — smaller than the move
// sequences, and the runtime cost of replaying 3807 lines (~8s) is paid here
// instead of in every browser on every page load.
//
//   node scripts/genOpeningPositions.cjs

const fs = require("fs");
const path = require("path");
const { Chess } = require("chess.js");

const readArray = (file, marker) => {
  const src = fs.readFileSync(file, "utf8");
  const at = src.indexOf(marker);
  if (at < 0) throw new Error(`no se encontró ${marker} en ${file}`);
  // Search after the `=`, not after the marker: the type annotation is
  // `string[]`, so looking for the first `[` found the one inside the TYPE and
  // then bracket-matched it to `[]` — an empty array, silently.
  const eq = src.indexOf("=", at);
  if (eq < 0) throw new Error(`no se encontró la asignación de ${marker}`);
  const start = src.indexOf("[", eq);
  // Scan to the matching bracket so a trailing `;` or later code can't confuse it.
  let depth = 0, end = start;
  for (let i = start; i < src.length; i++) {
    if (src[i] === "[") depth++;
    else if (src[i] === "]" && --depth === 0) { end = i + 1; break; }
  }
  // Pull out the string literals rather than JSON.parse-ing the slice: the
  // hand-curated array has JS comments and trailing commas inside it, which are
  // perfectly valid TypeScript and not valid JSON.
  const body = src.slice(start, end);
  return [...body.matchAll(/"([^"\\]*)"/g)].map((m) => m[1]);
};

const ecoLines = readArray(path.join("src", "lib", "ecoOpenings.ts"), "ECO_LINES");
const curated = readArray(path.join("src", "lib", "openingBook.ts"), "OPENING_LINES");
const lines = [...new Set([...ecoLines, ...curated])];

if (lines.length < 1000) {
  console.error(`[genOpeningPositions] ABORTA: solo ${lines.length} lineas de entrada.`);
  process.exit(1);
}

const hash = (str) => {
  let x = 5381;
  for (let i = 0; i < str.length; i++) x = ((x * 33) ^ str.charCodeAt(i)) >>> 0;
  return x;
};

const positions = new Set();
let replayed = 0, broken = 0;
for (const line of lines) {
  const board = new Chess();
  for (const san of String(line).split(/\s+/).filter(Boolean)) {
    try { if (!board.move(san)) { broken++; break; } } catch { broken++; break; }
    replayed++;
    // Placement + turn + castling rights. Move counters are excluded on purpose:
    // the same position reached in a different number of moves IS the same
    // position, which is the entire point of this file.
    const [placement, turn, castling] = board.fen().split(" ");
    positions.add(hash(`${placement} ${turn} ${castling}`));
  }
}

const list = [...positions].sort((a, b) => a - b);
if (list.length < 5000) {
  console.error(`[genOpeningPositions] ABORTA: solo ${list.length} posiciones.`);
  process.exit(1);
}

const header = [
  "// GENERATED by scripts/genOpeningPositions.cjs from the move sequences in",
  "// ecoOpenings.ts and openingBook.ts. Do not edit by hand.",
  "//",
  "// Hashed position keys (placement + side to move + castling rights) for every",
  "// prefix of every known opening line, so the book survives TRANSPOSITIONS.",
  "// Matching by move order left the book the moment a game reached a known",
  "// position via a different move order, which is common and was costing us ten",
  "// book moves in a Caro-Kann.",
  "//",
  `// ${list.length} positions from ${lines.length} lines.`,
  "export const ECO_POSITIONS: readonly number[] = ",
].join("\n");

fs.writeFileSync(
  path.join("src", "lib", "ecoPositions.ts"),
  `${header}${JSON.stringify(list)};\n`,
);

console.log(
  `lineas=${lines.length} jugadas=${replayed} lineas_truncadas=${broken} ` +
  `posiciones=${list.length} kb=${Math.round(JSON.stringify(list).length / 1024)}`,
);
